import { Descriptions, Empty, Modal, Spin, Table, Tag, Typography } from "antd";

const { Paragraph, Title } = Typography;

const STATUS_COLORS = {
  draft: "default",
  published: "success",
  archived: "warning",
};

const formatDateTime = (value) => {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;

  return date.toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

export default function SrsDocumentDetailModal({
  open,
  loading = false,
  document,
  onCancel,
}) {
  const requirementRows = Array.isArray(document?.requirements)
    ? document.requirements.map((item) => ({
        ...item,
        key: item.requirementId,
      }))
    : [];

  return (
    <Modal
      title={document?.documentTitle || "Document Detail"}
      open={open}
      onCancel={onCancel}
      footer={null}
      destroyOnClose
      centered
      width={1000}
      styles={{
        body: {
          maxHeight: "76vh",
          overflowY: "auto",
          paddingRight: 8,
        },
      }}
    >
      {loading ? (
        <div className="flex min-h-48 items-center justify-center">
          <Spin tip="Loading document..." />
        </div>
      ) : (
        <>
          <Descriptions
            bordered
            size="small"
            column={1}
            items={[
              {
                key: "title",
                label: "Title",
                children: document?.documentTitle || "-",
              },
              {
                key: "version",
                label: "Version",
                children: document?.version || "-",
              },
              {
                key: "status",
                label: "Status",
                children: (
                  <Tag
                    color={
                      STATUS_COLORS[String(document?.status).toLowerCase()] ||
                      "default"
                    }
                  >
                    {document?.status || "-"}
                  </Tag>
                ),
              },
              {
                key: "intro",
                label: "Introduction",
                children: document?.introduction || "-",
              },
              {
                key: "scope",
                label: "Scope",
                children: document?.scope || "-",
              },
              {
                key: "product",
                label: "Product Perspective",
                children: document?.productPerspective || "-",
              },
              {
                key: "users",
                label: "User Classes",
                children: document?.userClasses || "-",
              },
              {
                key: "env",
                label: "Operating Environment",
                children: document?.operatingEnvironment || "-",
              },
              {
                key: "assumptions",
                label: "Assumptions and Dependencies",
                children: document?.assumptionsDependencies || "-",
              },
              {
                key: "generatedBy",
                label: "Generated By",
                children: document?.generatedByName || "-",
              },
              {
                key: "generatedAt",
                label: "Generated At",
                children: formatDateTime(document?.generatedAt),
              },
              {
                key: "updatedAt",
                label: "Updated At",
                children: formatDateTime(document?.updatedAt),
              },
            ]}
          />

          <div className="mt-6">
            <Title level={5}>Included Requirements</Title>
            {requirementRows.length ? (
              <Table
                columns={[
                  {
                    title: "SECTION",
                    dataIndex: "sectionNumber",
                    key: "sectionNumber",
                    width: 120,
                  },
                  {
                    title: "REQ CODE",
                    dataIndex: "requirementCode",
                    key: "requirementCode",
                    width: 140,
                  },
                  {
                    title: "TITLE",
                    dataIndex: "title",
                    key: "title",
                    width: 240,
                  },
                  {
                    title: "TYPE",
                    dataIndex: "requirementType",
                    key: "requirementType",
                    width: 150,
                  },
                  {
                    title: "PRIORITY",
                    dataIndex: "priority",
                    key: "priority",
                    width: 120,
                    render: (value) => <Tag>{value || "-"}</Tag>,
                  },
                  {
                    title: "DESCRIPTION",
                    dataIndex: "description",
                    key: "description",
                    render: (value) => (
                      <Paragraph
                        className="!mb-0"
                        ellipsis={{ rows: 2, expandable: true }}
                      >
                        {value || "-"}
                      </Paragraph>
                    ),
                  },
                ]}
                dataSource={requirementRows}
                rowKey="key"
                pagination={false}
                scroll={{ x: 1080 }}
              />
            ) : (
              <Empty
                image={Empty.PRESENTED_IMAGE_SIMPLE}
                description="This document does not include any requirements."
              />
            )}
          </div>
        </>
      )}
    </Modal>
  );
}
