import {
  DownloadOutlined,
  EditOutlined,
  EyeOutlined,
  RedoOutlined,
} from "@ant-design/icons";
import { Button, Popover, Space, Table, Tag } from "antd";

const STATUS_COLORS = {
  draft: "default",
  published: "success",
  archived: "warning",
};

const renderActionPopover = (content, node) => (
  <Popover
    content={<span className="text-white">{content}</span>}
    trigger="hover"
    placement="top"
    color="#1f1f1f"
  >
    {node}
  </Popover>
);

export default function SrsDocumentsTable({
  loading = false,
  rows = [],
  onView,
  onEdit,
  onRegenerate,
  onDownloadHtml,
  onDownloadDoc,
}) {
  const columns = [
    {
      title: "TITLE",
      dataIndex: "documentTitle",
      key: "documentTitle",
      width: 260,
      render: (value) => (
        <span className="text-sm font-semibold text-slate-900">{value}</span>
      ),
    },
    {
      title: "VERSION",
      dataIndex: "version",
      key: "version",
      width: 120,
    },
    {
      title: "STATUS",
      dataIndex: "status",
      key: "status",
      width: 140,
      render: (value) => (
        <Tag color={STATUS_COLORS[String(value).toLowerCase()] || "default"}>
          {value}
        </Tag>
      ),
    },
    {
      title: "REQUIREMENTS",
      dataIndex: "requirementsCount",
      key: "requirementsCount",
      width: 140,
    },
    {
      title: "GENERATED BY",
      dataIndex: "generatedByName",
      key: "generatedByName",
      width: 180,
    },
    {
      title: "GENERATED AT",
      dataIndex: "generatedAtLabel",
      key: "generatedAtLabel",
      width: 180,
    },
    {
      title: "UPDATED",
      dataIndex: "updatedAtLabel",
      key: "updatedAtLabel",
      width: 180,
    },
    {
      title: "ACTIONS",
      key: "actions",
      width: 150,
      fixed: "right",
      render: (_, record) => (
        <Space size="small" wrap>
          {renderActionPopover(
            "View document details",
            <Button
              size="small"
              icon={<EyeOutlined />}
              onClick={() => onView(record)}
            />,
          )}
          {renderActionPopover(
            "Edit document",
            <Button
              size="small"
              icon={<EditOutlined />}
              onClick={() => onEdit(record)}
              className="text-white"
            />,
          )}
          {renderActionPopover(
            "Regenerate document",
            <Button
              size="small"
              icon={<RedoOutlined />}
              onClick={() => onRegenerate(record)}
            />,
          )}
          {renderActionPopover(
            "Download HTML file",
            <Button
              size="small"
              icon={<DownloadOutlined />}
              onClick={() => onDownloadHtml(record)}
            />,
          )}
          {renderActionPopover(
            "Download Word file",
            <Button
              size="small"
              icon={<DownloadOutlined />}
              onClick={() => onDownloadDoc(record)}
            />,
          )}
        </Space>
      ),
    },
  ];

  return (
    <Table
      loading={loading}
      columns={columns}
      dataSource={rows}
      rowKey="key"
      pagination={{ pageSize: 6, showSizeChanger: false }}
      locale={{ emptyText: "No SRS documents found" }}
      scroll={{ x: 1680 }}
    />
  );
}
